### ISSUE TITLE
Missing dependency babel-preset-vue

### ISSUE THREAD

**Issue by chepe263** [guastallaigor/vue-list-picker#1]
**Describe the bug**
Missing dependency `babel-preset-vue`

**To Reproduce**

1. clone the repo locally
2. cd repo
3. npm install
4. npm run storybook
>  @storybook/vue v5.1.11
> info
> info => Loading presets
> info => Loading presets
> 
> WARN Broken build, fix the error below.
> WARN You may need to refresh the browser.
> 
> ERR! Error: Cannot find module 'babel-preset-vue'

**Expected behavior**
Run storybook

**Environment:**
 - OS: Windows
 - Browser: none
 - Build environment (i.e. NodeJS): 
    > node v12.8.0
    > npm 6.10.2

**Suggestion(s) for fixing this issue**
add babel-preset-vue as a dependency
`npm install babel-preset-vue --save`

**Comment by guastallaigor** [comment]
Hello. Sorry about the delay @chepe263, I'm currently on vacation, but this feels a bit strange to me because the bug **only** happens using `npm`, using `yarn` this bug doesn't happen.
But no problem, I will add `babel-preset-vue` as a dev dependency :+1:
