### ISSUE TITLE
How to add a custom style for button-class?

### ISSUE THREAD

**Issue by dinhthang12t** [guastallaigor/vue-list-picker#2]
Hi, thank you very much for your work. 
Can you show me how to add a custom style for button-class?

**Comment by guastallaigor** [comment]
Hello @dinhthang12t, sorry about the delay.
Not sure if I understand what you meant. 
Right now, to change all the buttons design you can use the `button-class` prop. This will add a custom class to all the buttons inside of the component. So this custom class you will need to create it manually in your own code.

Example:
```html
<template>
  <vue-list-picker 
    :left-items="leftItems"
    :right-items="rightItems"
    button-class="custom-button"
    />
</template>

<script>
export default {  
  data() {
    const example1 = {
      key: 1,
      content: 'Item 1'
    }
    const example2 = {
      key: 2,
      content: 'Item 2'
    }
    const example3 = {
      key: 3,
      content: 'Item 3'
    }
    const example4 = {
      key: 4,
      content: 'Item 4'
    }
    
    const leftItems = [example1, example2]
    const rightItems = [example3, example4]

    return { leftItems, rightItems }
  }
}
</script>

<style>
.custom-button {
  border-radius: 50px;
  background: red;
  color: #fff;
}
</style>
```

To change the default svg icons inside the buttons, you can use the slots and add your own icon or anything that you want in your own code.
There's no prop to add inline-style.
If I didn't answer your question correctly, please let me know.
Thank you.

**Comment by dinhthang12t** [comment]
Thank you very much.
You save my life

**Comment by steffao** [comment]
Hi @guastallaigor , thanks for the work you did. This is the only vue list picker I found in vue 3.

On my app, the icons doesn't show. So, I tried to use the slots to add my own icon but impossible to do it. Can you show an example please?
